### ISSUE TITLE
RenderFrame should be called at least once in CubeDemo

### ISSUE THREAD

**Issue by federgraph** [Memnarch/SoftwareRenderer#1]
There is a problem in CubeDemo if you set GameTimer to false.

> ( It makes the IDE hang! )

I don't know why but it helps to call RenderFrame at least once.

```pascal
procedure TForm1.FormCreate(Sender: TObject);
begin
  ... 
  { call RenderFrame at least once, in case GameTimer is initially disabled }
  FSoftwareRenderer.RenderFrame(Canvas); // <--
  GameTimer.Enabled := False; //True;
end;
```

**Comment by Memnarch** [comment]
That sounds strange. Ahh maybe because, when exiting(i assume that's when it hangs?) it waits for his workers.

**Comment by federgraph** [comment]
Using Rio CE. Hang happens immediately after running through FormCreate, if GameTimer.Enabled is set to False instead of True. Can you not reproduce?

**Comment by Memnarch** [comment]
It doesn't hang for me. It does not produce any picture, which is to expect. But the project closes fine, except for an AV on missing drawcalls in the workers. But no, i can not reproduce a hang.

10.2

**Comment by Memnarch** [comment]
However, i'll take a lock at the AV as workers are suposed to finish without errors, even when not used once. That's an error for sure.

**Comment by federgraph** [comment]
Ok, thanks. BTW, I handle VK_F2 to toggle GameTimer.Enabled, in the Demo.

As a sidenote, would you consider to give every pas file a BOM, so that the Delphi IDE will report UTF-8 as the encoding?

And also, I dared to change the formatting in my local copy, while reading.
```pascal
    procedure Vertex(
      const AWorld: TMatrix4x4;
      const AProjection: TMatrix4x4;
      var AVertex: TFloat4;
      const AVInput: TVertexShaderInput;
      const AAttributeBuffer: TShader<TTexturePSInput>.PAttributeType); override; final;

function CalculateFactorB(const AVecA, AVecB, AVecC: TFloat4; AValA, AValB, AValC: Single): Single;
begin
  Result := AValA * (AVecB.X - AvecC.X) +
            AValB * (AvecC.X - AvecA.X) +
            AValC * (AVecA.X - AvecB.X);
end;
```

**Comment by federgraph** [comment]
Update: Today, I could not reproduce the hang at start up but instead I saw the AV when closing, and it did hang then.

I have one mesh in my application, and I am used to rotate with the mouse and change the shape of  the mesh with the wheel. That is why I do not need the timer. How do I produce a picture without running a timer?

```
  if (Key = VK_F2) then
  begin
    GameTimer.Enabled := not GameTimer.Enabled;
  end;
  if (Key = VK_F3) then
  begin
    GameTimerTimer(nil);
  end;
```

Found out that I have to hit F3 twice to see a picture. It is ok to do one call to GameTimerTimer(nil) in FormCreate and the second with the key.

**Comment by Memnarch** [comment]
The purpose of the Cubedemo is to showcase a simple realtime demo. Therefore without the timer, you won't see any results. And for any future updates, the goal is to keep it realtime interactive, as i'm not aiming for an offline renderer.

The reason you had to do it twice is because of the asnyc processing. The current RenderFrame prepares the workload for the next rund and blits the result of the previous workers run to the screen. That's something games do aswell by preparing multiple frames in advance and let the gpu work on the prepared frames.

**Comment by Memnarch** [comment]
av fixed. it should no longer cause issues :)
